Much MPI stuff stripped out and/or tidied.  First part of the MPI rewrite.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1016,17 +1016,13 @@ Optional Features:
   --disable-libtool-lock  avoid locking (might break parallel builds)
   --enable-g=yes/no             compile with symbolic debug information. default=yes
   --enable-debug=no/minimum/yes turn on debugging. default=$debug_default
-  --enable-memory-debug           turn on memory access debugging. default=no
-  --enable-ansi                   turn on strict ansi. default=no
-  --enable-missing-prototypes     turn on missing prototype checks. default=no
-  --enable-threads                turn on multi-thread support. default=no
-                          (=no will override --with-threads)
-  --enable-mpi                    turn on MPI support. default=no
-                          (=no will override --with-mpi)
-  --enable-pvm                    turn on PVM3 support. default=no
-                          (=no will override --with-pvm)
+  --enable-memory-debug=yes/no  turn on memory access debugging. default=no
+  --enable-ansi=yes/no          turn on strict ansi. default=no
+  --enable-missing-prototypes=yes/no turn on missing prototype checks. default=no
+  --enable-threads=yes/no       turn on multi-thread support. default=no
+  --enable-mpi=yes/no           turn on MPI support. default=no
   --enable-slang=yes/no         use S-Lang for scripting. default=yes
-  --enable-profile                turn on profiling. default=no
+  --enable-profile=yes/no       turn on profiling. default=no
   --enable-efence=yes/no        use Electric Fence for memory debugging. default=no
   --enable-padding=yes/no       use memory padding for overflow detection. default=no
   --enable-memory-chunks=yes/no use memory chunk allocation routines. default=yes
@@ -1577,7 +1573,7 @@ PACKAGE=gaul-devel
 
 GA_MAJOR_VERSION=0
 GA_MINOR_VERSION=1846
-GA_PATCH_VERSION=1
+GA_PATCH_VERSION=2
 GA_VERSION=${GA_MAJOR_VERSION}.${GA_MINOR_VERSION}-${GA_PATCH_VERSION}
 
 #
@@ -4721,7 +4717,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4724 "configure"' > conftest.$ac_ext
+  echo '#line 4720 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5250,7 +5246,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5253: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5249: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6434,7 +6430,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6437 "configure"' > conftest.$ac_ext
+    echo '#line 6433 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7106,7 +7102,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7109 "configure"
+#line 7105 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7204,7 +7200,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7207 "configure"
+#line 7203 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -8002,13 +7998,6 @@ if test "${enable_mpi+set}" = set; then
 else
   enable_mpi=no
 fi;
-# Check whether --enable-pvm or --disable-pvm was given.
-if test "${enable_pvm+set}" = set; then
-  enableval="$enable_pvm"
-
-else
-  enable_pvm=no
-fi;
 # Check whether --enable-slang or --disable-slang was given.
 if test "${enable_slang+set}" = set; then
   enableval="$enable_slang"
@@ -8105,41 +8094,230 @@ fi
 #
 # Setup MPI compilation
 #
-echo "$as_me:$LINENO: checking for MPI use" >&5
-echo $ECHO_N "checking for MPI use... $ECHO_C" >&6
+echo "$as_me:$LINENO: checking for whether to use MPI" >&5
+echo $ECHO_N "checking for whether to use MPI... $ECHO_C" >&6
 if test "x$enable_mpi" != "xyes"; then
-  echo "$as_me:$LINENO: result: don't use" >&5
-echo "${ECHO_T}don't use" >&6
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
   enable_mpi=no
   MPIFLAGS=""
   MPILIBS=""
+  result=0
 else
-  echo "$as_me:$LINENO: result: use" >&5
-echo "${ECHO_T}use" >&6
-
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_MPI 1
-_ACEOF
-
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
   MPIFLAGS=""
   MPILIBS=""
+  result=1
+#
+# Check for MPI version.
+#
+  if test "x$MPIFLAGS" != "x" || test "x$MPILIBS" != "x"; then
+	  # User defined the additional LIBS and CFLAGS stuff :-).
+    echo "$as_me:$LINENO: checking for MPI_Init in -lmpi" >&5
+echo $ECHO_N "checking for MPI_Init in -lmpi... $ECHO_C" >&6
+if test "${ac_cv_lib_mpi_MPI_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpi  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char MPI_Init ();
+int
+main ()
+{
+MPI_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mpi_MPI_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mpi_MPI_Init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_MPI_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_mpi_MPI_Init" >&6
+if test $ac_cv_lib_mpi_MPI_Init = yes; then
+  LIBS="$LIBS $MPILIBS", CFLAGS="$CFLAGS $MPIFLAGS"
+else
+  { { echo "$as_me:$LINENO: error: Unable to compile with specified MPI implementation.  Check MPIFLAGS and MPILIBS environment variables" >&5
+echo "$as_me: error: Unable to compile with specified MPI implementation.  Check MPIFLAGS and MPILIBS environment variables" >&2;}
+   { (exit or configure with '--enable-mpi=no' to disable MPI use.); exit or configure with '--enable-mpi=no' to disable MPI use.; }; }
 fi
 
-echo "$as_me:$LINENO: checking for PVM3 use" >&5
-echo $ECHO_N "checking for PVM3 use... $ECHO_C" >&6
-if test "x$enable_pvm" != "xyes"; then
-	echo "$as_me:$LINENO: result: don't use" >&5
-echo "${ECHO_T}don't use" >&6
-  enable_pvm=no
-else
-  echo "$as_me:$LINENO: result: use" >&5
-echo "${ECHO_T}use" >&6
+  else
+	  # User didn't define the additional LIBS and CFLAGS stuff, so we must try to guess it :-(
+    { echo "$as_me:$LINENO: WARNING: You are advised to specify requirements of your MPI implementation via the MPIFLAGS and MPILIBS environment variables." >&5
+echo "$as_me: WARNING: You are advised to specify requirements of your MPI implementation via the MPIFLAGS and MPILIBS environment variables." >&2;}
+    # Try LAM
+    MPIFLAGS="-D_REENTRANT"
+    MPILIBS="-llammpio -llamf77mpi -lmpi -llam -lutil -lpthread"
 
-cat >>confdefs.h <<\_ACEOF
-#define HAVE_PVM3 1
+    echo "$as_me:$LINENO: checking for MPI_Init in -lmpi" >&5
+echo $ECHO_N "checking for MPI_Init in -lmpi... $ECHO_C" >&6
+if test "${ac_cv_lib_mpi_MPI_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpi  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char MPI_Init ();
+int
+main ()
+{
+MPI_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mpi_MPI_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mpi_MPI_Init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_MPI_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_mpi_MPI_Init" >&6
+if test $ac_cv_lib_mpi_MPI_Init = yes; then
+  LIBS="$LIBS $MPILIBS", CFLAGS="$CFLAGS $MPIFLAGS"
+else
+  result=0
+fi
+
+    if test result = 0; then
+      # Try MPICH
+      result=1
+      MPIFLAGS="-DUSE_STDARG -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_UNISTD_H=1 -DHAVE_STDARG_H=1 -DUSE_STDARG=1 -DMALLOC_RET_VOID=1"
+      MPILIBS="-lmpich"
+
+      echo "$as_me:$LINENO: checking for MPI_Init in -lmpi" >&5
+echo $ECHO_N "checking for MPI_Init in -lmpi... $ECHO_C" >&6
+if test "${ac_cv_lib_mpi_MPI_Init+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lmpi  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char MPI_Init ();
+int
+main ()
+{
+MPI_Init ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_mpi_MPI_Init=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_mpi_MPI_Init=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_mpi_MPI_Init" >&5
+echo "${ECHO_T}$ac_cv_lib_mpi_MPI_Init" >&6
+if test $ac_cv_lib_mpi_MPI_Init = yes; then
+  LIBS="$LIBS $MPILIBS", CFLAGS="$CFLAGS $MPIFLAGS"
+else
+  result=0
+fi
+
+    fi
+  fi
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_MPI ${result}
 _ACEOF
 
-fi
 
 echo "$as_me:$LINENO: checking whether to disable memory chunk allocation" >&5
 echo $ECHO_N "checking whether to disable memory chunk allocation... $ECHO_C" >&6
@@ -8429,6 +8607,10 @@ echo "$as_me:$LINENO: result: $ac_cv_lib_efence_malloc" >&5
 echo "${ECHO_T}$ac_cv_lib_efence_malloc" >&6
 if test $ac_cv_lib_efence_malloc = yes; then
   LIBS="$LIBS -lefence"
+else
+  { { echo "$as_me:$LINENO: error: Unable to detect working Electric Fence installation" >&5
+echo "$as_me: error: Unable to detect working Electric Fence installation" >&2;}
+   { (exit 1); exit 1; }; }
 fi
 
 else
