Updated configuration files for successful compilation on RedHat 8.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1930,16 +1930,6 @@ _ACEOF
 
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_SLANG 0
-_ACEOF
-
-
-cat >>confdefs.h <<\_ACEOF
-#define MEMORY_ALIGN_SIZE 0
-_ACEOF
-
-
-cat >>confdefs.h <<\_ACEOF
 #define MEMORY_ALLOC_DEBUG 0
 _ACEOF
 
@@ -4393,7 +4383,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4396 "configure"' > conftest.$ac_ext
+  echo '#line 4386 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -4929,7 +4919,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:4932: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:4922: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6722,7 +6712,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6725 "configure"
+#line 6715 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -6820,7 +6810,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 6823 "configure"
+#line 6813 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7893,94 +7883,6 @@ fi
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
-fi
-
-# Check for S-Lang.
-echo "$as_me:$LINENO: checking whether to link S-Lang scripting engine" >&5
-echo $ECHO_N "checking whether to link S-Lang scripting engine... $ECHO_C" >&6
-if test "x$enable_slang" = "xyes"; then
-  echo "$as_me:$LINENO: result: yes" >&5
-echo "${ECHO_T}yes" >&6
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_SLANG 1
-_ACEOF
-
-  WILL_USE_SLANG="yes"
-  LIBS="$LIBS -lslang"
-  INCLUDES="$INCLUDES -I/usr/include/slang/"
-  CFLAGS="$CFLAGS -I/usr/include/slang/" # FIXME: Kludge!
-  echo "$as_me:$LINENO: checking for SLang_init_slang in -lslang" >&5
-echo $ECHO_N "checking for SLang_init_slang in -lslang... $ECHO_C" >&6
-if test "${ac_cv_lib_slang_SLang_init_slang+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_check_lib_save_LIBS=$LIBS
-LIBS="-lslang  $LIBS"
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-/* Override any gcc2 internal prototype to avoid an error.  */
-#ifdef __cplusplus
-extern "C"
-#endif
-/* We use char because int might match the return type of a gcc2
-   builtin and then its argument prototype would still apply.  */
-char SLang_init_slang ();
-#ifdef F77_DUMMY_MAIN
-#  ifdef __cplusplus
-     extern "C"
-#  endif
-   int F77_DUMMY_MAIN() { return 1; }
-#endif
-int
-main ()
-{
-SLang_init_slang ();
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_lib_slang_SLang_init_slang=yes
-else
-  echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-ac_cv_lib_slang_SLang_init_slang=no
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-LIBS=$ac_check_lib_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_lib_slang_SLang_init_slang" >&5
-echo "${ECHO_T}$ac_cv_lib_slang_SLang_init_slang" >&6
-if test $ac_cv_lib_slang_SLang_init_slang = yes; then
-  LIBS="$LIBS -lslang"
-     INCLUDES="$INCLUDES -I/usr/include/slang/"
-else
-  { { echo "$as_me:$LINENO: error: GAUL requires the S-Lang library for full functionality.  see http://space.mit.edu/pub/davis/slang/  Or configure with '--enable-slang=no' for reduced version." >&5
-echo "$as_me: error: GAUL requires the S-Lang library for full functionality.  see http://space.mit.edu/pub/davis/slang/  Or configure with '--enable-slang=no' for reduced version." >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-  cat >>confdefs.h <<\_ACEOF
-#define HAVE_SLANG 0
-_ACEOF
-
-  WILL_USE_SLANG="no"
 fi
 
 # Optimisations etc. for the GNU gcc compiler.
@@ -10413,60 +10315,6 @@ _ACEOF
 fi
 
 
-echo "$as_me:$LINENO: checking memory alignment" >&5
-echo $ECHO_N "checking memory alignment... $ECHO_C" >&6
-if test "${MEMORY_ALIGN_SIZE+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  if test "$cross_compiling" = yes; then
-  MEMORY_ALIGN_SIZE=8
-else
-  cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-#include "confdefs.h"
-
-#include <stdio.h>
-#include <stdlib.h>
-int main(void)
-  {
-  FILE *f=fopen("conftestval", "w");
-  if (!f) exit(1);
-  fprintf(f, "%d\n", (unsigned int) sizeof(long)>sizeof(void *)?sizeof(long):sizeof(void *));
-  exit(0);
-  }
-
-_ACEOF
-rm -f conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  MEMORY_ALIGN_SIZE=`cat conftestval`
-else
-  echo "$as_me: program exited with status $ac_status" >&5
-echo "$as_me: failed program was:" >&5
-cat conftest.$ac_ext >&5
-( exit $ac_status )
-MEMORY_ALIGN_SIZE=0
-fi
-rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
-fi
-fi
-
-echo "$as_me:$LINENO: result: $MEMORY_ALIGN_SIZE" >&5
-echo "${ECHO_T}$MEMORY_ALIGN_SIZE" >&6
-cat >>confdefs.h <<_ACEOF
-#define MEMORY_ALIGN_SIZE $MEMORY_ALIGN_SIZE
-_ACEOF
-
-# undefine([MEMORY_ALIGN_SIZE])
-
 INCLUDES="$INCLUDES -I../util/"
 CFLAGS="$CFLAGS -I../util/ -I../src/" # FIXME: Kludge!
 
@@ -11081,6 +10929,150 @@ elif test "x$target" = "xsparc-sun-solaris2.8"; then
 _ACEOF
 
 fi
+
+# Check for S-Lang.
+echo "$as_me:$LINENO: checking whether to link S-Lang scripting engine" >&5
+echo $ECHO_N "checking whether to link S-Lang scripting engine... $ECHO_C" >&6
+if test "x$enable_slang" = "xyes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SLANG 1
+_ACEOF
+
+  WILL_USE_SLANG="yes"
+  LIBS="$LIBS -lslang"
+  INCLUDES="$INCLUDES -I/usr/include/slang/"
+  CFLAGS="$CFLAGS -I/usr/include/slang/" # FIXME: Kludge!
+  echo "$as_me:$LINENO: checking for SLang_init_slang in -lslang" >&5
+echo $ECHO_N "checking for SLang_init_slang in -lslang... $ECHO_C" >&6
+if test "${ac_cv_lib_slang_SLang_init_slang+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lslang  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SLang_init_slang ();
+#ifdef F77_DUMMY_MAIN
+#  ifdef __cplusplus
+     extern "C"
+#  endif
+   int F77_DUMMY_MAIN() { return 1; }
+#endif
+int
+main ()
+{
+SLang_init_slang ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_slang_SLang_init_slang=yes
+else
+  echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+ac_cv_lib_slang_SLang_init_slang=no
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_slang_SLang_init_slang" >&5
+echo "${ECHO_T}$ac_cv_lib_slang_SLang_init_slang" >&6
+if test $ac_cv_lib_slang_SLang_init_slang = yes; then
+  LIBS="$LIBS -lslang"
+     INCLUDES="$INCLUDES -I/usr/include/slang/"
+else
+  { { echo "$as_me:$LINENO: error: GAUL requires the S-Lang library for full functionality.  see http://space.mit.edu/pub/davis/slang/  Or configure with '--enable-slang=no' for reduced version." >&5
+echo "$as_me: error: GAUL requires the S-Lang library for full functionality.  see http://space.mit.edu/pub/davis/slang/  Or configure with '--enable-slang=no' for reduced version." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SLANG 0
+_ACEOF
+
+  WILL_USE_SLANG="no"
+fi
+
+echo "$as_me:$LINENO: checking memory alignment" >&5
+echo $ECHO_N "checking memory alignment... $ECHO_C" >&6
+if test "${MEMORY_ALIGN_SIZE+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  if test "$cross_compiling" = yes; then
+  MEM_ALIGN_SIZE=8
+else
+  cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+#include "confdefs.h"
+
+#include <stdio.h>
+#include <stdlib.h>
+int main(void)
+  {
+  FILE *f=fopen("conftestval", "w");
+  if (!f) exit(1);
+  fprintf(f, "%d\n", (unsigned int) sizeof(long)>sizeof(void *)?sizeof(long):sizeof(void *));
+  exit(0);
+  }
+
+_ACEOF
+rm -f conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  MEM_ALIGN_SIZE=`cat conftestval`
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+cat conftest.$ac_ext >&5
+( exit $ac_status )
+MEM_ALIGN_SIZE=4
+fi
+rm -f core core.* *.core conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+fi
+
+echo "$as_me:$LINENO: result: ${MEM_ALIGN_SIZE}" >&5
+echo "${ECHO_T}${MEM_ALIGN_SIZE}" >&6
+
+cat >>confdefs.h <<_ACEOF
+#define MEMORY_ALIGN_SIZE ${MEM_ALIGN_SIZE}
+_ACEOF
+
 
 temp=`make -version -f \dev\null 2>&1 | grep GNU`
 if test "x$temp" = "x"; then
