Added a configure option to make use of Intel's icc compiler's autoparallelisation features more easily.  Also adjusted code to reduce number of remarks/warnings given upon compilation.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1020,6 +1020,7 @@ Optional Features:
   --enable-ansi=yes/no          turn on strict ansi. default=no
   --enable-missing-prototypes=yes/no turn on missing prototype checks. default=no
   --enable-pthread=yes/no       turn on multi-thread support using pthread. default=yes
+  --enable-parallel=yes/no      turn on auto-parallelisation for Intel's icc compiler. default=no
   --enable-mpi=yes/no           turn on MPI support. default=no
   --enable-slang=yes/no         use S-Lang for scripting. default=yes
   --enable-profile=yes/no       turn on profiling. default=no
@@ -4717,7 +4718,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4720 "configure"' > conftest.$ac_ext
+  echo '#line 4721 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5246,7 +5247,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5249: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5250: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6430,7 +6431,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6433 "configure"' > conftest.$ac_ext
+    echo '#line 6434 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7102,7 +7103,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7105 "configure"
+#line 7106 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7200,7 +7201,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7203 "configure"
+#line 7204 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7991,6 +7992,13 @@ if test "${enable_pthread+set}" = set; then
 else
   enable_pthread=yes
 fi;
+# Check whether --enable-parallel or --disable-parallel was given.
+if test "${enable_parallel+set}" = set; then
+  enableval="$enable_parallel"
+
+else
+  enable_parallel=no
+fi;
 # Check whether --enable-mpi or --disable-mpi was given.
 if test "${enable_mpi+set}" = set; then
   enableval="$enable_mpi"
@@ -8161,6 +8169,20 @@ cat >>confdefs.h <<_ACEOF
 #define HAVE_PTHREADS ${result}
 _ACEOF
 
+
+# A sanity check.
+if test "x$enable_parallel" = "xyes"; then
+echo "$as_me:$LINENO: checking whether to autoparallelise code" >&5
+echo $ECHO_N "checking whether to autoparallelise code... $ECHO_C" >&6
+ if test "x$CC" = "xicc"; then
+   echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+ else
+    { { echo "$as_me:$LINENO: error: --enable-parallel=yes can only be used with Intel's icc compiler." >&5
+echo "$as_me: error: --enable-parallel=yes can only be used with Intel's icc compiler." >&2;}
+   { (exit 1); exit 1; }; }
+  fi
+fi
 
 #
 # Setup MPI compilation
@@ -8880,6 +8902,13 @@ case $CC in
       *[\ \	]-ipo[\ \	]*) ;;
       *) CFLAGS="$CFLAGS -ipo -ipo_obj" ;;
     esac
+
+    if test "x$enable_parallel" = "xyes"; then
+      case " $CFLAGS " in
+        *[\ \	]-parallel[\ \	]*) ;;
+        *) CFLAGS="$CFLAGS -parallel -parthreshold50 -par_report3" ;;
+      esac
+    fi
 
     if test "x$enable_prof" = "xyes"; then
       case " $CFLAGS " in
