OpenMP parallelisation added.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -467,7 +467,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LT_RELEASE LT_CURRENT LT_REVISION INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL GA_MAJOR_VERSION GA_MINOR_VERSION GA_PATCH_VERSION GA_VERSION GA_VERSION_STRING MPIFLAGS MPILIBS GA_UNAME_STRING GA_BUILD_DATE_STRING V3_QUICK W32_CRIPPLED HAVE_SLANG HAVE_MPI HAVE_PTHREADS GA_NUM_PROCESSES_ENVVAR_STRING MEMORY_ALLOC_DEBUG MEMORY_ALLOC_SAFE MEMORY_CHUNKS_MIMIC LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os LT_RELEASE LT_CURRENT LT_REVISION INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE LN_S ECHO RANLIB ac_ct_RANLIB CPP EGREP LIBTOOL GA_MAJOR_VERSION GA_MINOR_VERSION GA_PATCH_VERSION GA_VERSION GA_VERSION_STRING MPIFLAGS MPILIBS GA_UNAME_STRING GA_BUILD_DATE_STRING V3_QUICK W32_CRIPPLED HAVE_SLANG HAVE_MPI HAVE_PTHREADS USE_OPENMP GA_NUM_PROCESSES_ENVVAR_STRING MEMORY_ALLOC_DEBUG MEMORY_ALLOC_SAFE MEMORY_CHUNKS_MIMIC LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1020,6 +1020,7 @@ Optional Features:
   --enable-ansi=yes/no          turn on strict ansi. default=no
   --enable-missing-prototypes=yes/no turn on missing prototype checks. default=no
   --enable-pthread=yes/no       turn on multi-thread support using pthread. default=yes
+  --enable-openmp=yes/no        turn on multi-thread support using OpenMP. default=no
   --enable-parallel=yes/no      turn on auto-parallelisation for Intel's icc compiler. default=no
   --enable-mpi=yes/no           turn on MPI support. default=no
   --enable-slang=yes/no         use S-Lang for scripting. default=yes
@@ -4718,7 +4719,7 @@ test "x$enable_libtool_lock" != xno && enable_libtool_lock=yes
 case $host in
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4721 "configure"' > conftest.$ac_ext
+  echo '#line 4722 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -5247,7 +5248,7 @@ chmod -w .
 save_CFLAGS="$CFLAGS"
 CFLAGS="$CFLAGS -o out/conftest2.$ac_objext"
 compiler_c_o=no
-if { (eval echo configure:5250: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
+if { (eval echo configure:5251: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>out/conftest.err; } && test -s out/conftest2.$ac_objext; then
   # The compiler can only warn and ignore the option if not recognized
   # So say no if there are warnings
   if test -s out/conftest.err; then
@@ -6431,7 +6432,7 @@ linux-gnu*)
   libsuff=
   case "$host_cpu" in
   x86_64*|s390x*)
-    echo '#line 6434 "configure"' > conftest.$ac_ext
+    echo '#line 6435 "configure"' > conftest.$ac_ext
     if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -7103,7 +7104,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7106 "configure"
+#line 7107 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7201,7 +7202,7 @@ else
     lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 7204 "configure"
+#line 7205 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -7992,6 +7993,13 @@ if test "${enable_pthread+set}" = set; then
 else
   enable_pthread=yes
 fi;
+# Check whether --enable-openmp or --disable-openmp was given.
+if test "${enable_openmp+set}" = set; then
+  enableval="$enable_openmp"
+
+else
+  enable_openmp=no
+fi;
 # Check whether --enable-parallel or --disable-parallel was given.
 if test "${enable_parallel+set}" = set; then
   enableval="$enable_parallel"
@@ -8170,6 +8178,37 @@ cat >>confdefs.h <<_ACEOF
 _ACEOF
 
 
+#
+# Check for OpenMP
+#
+echo "$as_me:$LINENO: checking whether to use OpenMP" >&5
+echo $ECHO_N "checking whether to use OpenMP... $ECHO_C" >&6
+if test "x$enable_openmp" = "xyes"; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  WILL_USE_OPENMP="yes"
+  USE_OPENMP=1
+  result=1
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+  WILL_USE_OPENMP="no"
+  result=0
+  USE_OPENMP=0
+fi
+
+cat >>confdefs.h <<_ACEOF
+#define USE_OPENMP ${result}
+_ACEOF
+
+
+# A sanity check.
+if test "x$WILL_USE_PTHREADS" = "xyes" && test "x$WILL_USE_OPENMP" = "xyes"; then
+ { { echo "$as_me:$LINENO: error: Can not simultaneously use OpenMP and pthreads for thread-level parallelisation." >&5
+echo "$as_me: error: Can not simultaneously use OpenMP and pthreads for thread-level parallelisation." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
 # A sanity check.
 if test "x$enable_parallel" = "xyes"; then
 echo "$as_me:$LINENO: checking whether to autoparallelise code" >&5
@@ -8178,7 +8217,7 @@ echo $ECHO_N "checking whether to autoparallelise code... $ECHO_C" >&6
    echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
  else
-    { { echo "$as_me:$LINENO: error: --enable-parallel=yes can only be used with Intel's icc compiler." >&5
+   { { echo "$as_me:$LINENO: error: --enable-parallel=yes can only be used with Intel's icc compiler." >&5
 echo "$as_me: error: --enable-parallel=yes can only be used with Intel's icc compiler." >&2;}
    { (exit 1); exit 1; }; }
   fi
@@ -8813,6 +8852,7 @@ _ACEOF
 
 
 
+
 #
 # Compiler specific switches.
 #
@@ -8902,6 +8942,13 @@ case $CC in
       *[\ \	]-ipo[\ \	]*) ;;
       *) CFLAGS="$CFLAGS -ipo -ipo_obj" ;;
     esac
+
+    if test "x$enable_openmp" = "xyes"; then
+      case " $CFLAGS " in
+        *[\ \	]-openmp[\ \	]*) ;;
+        *) CFLAGS="$CFLAGS -openmp -openmp_report2" ;;
+      esac
+    fi
 
     if test "x$enable_parallel" = "xyes"; then
       case " $CFLAGS " in
@@ -12691,6 +12738,7 @@ W32_CRIPPLED=$W32_CRIPPLED
 HAVE_SLANG=$HAVE_SLANG
 HAVE_MPI=$HAVE_MPI
 HAVE_PTHREADS=$HAVE_PTHREADS
+USE_OPENMP=$USE_OPENMP
 GA_NUM_PROCESSES_ENVVAR_STRING=$GA_NUM_PROCESSES_ENVVAR_STRING
 GA_NUM_THREADS_ENVVAR_STRING=$GA_NUM_THREADS_ENVVAR_STRING
 
@@ -12871,6 +12919,7 @@ s,@W32_CRIPPLED@,$W32_CRIPPLED,;t t
 s,@HAVE_SLANG@,$HAVE_SLANG,;t t
 s,@HAVE_MPI@,$HAVE_MPI,;t t
 s,@HAVE_PTHREADS@,$HAVE_PTHREADS,;t t
+s,@USE_OPENMP@,$USE_OPENMP,;t t
 s,@GA_NUM_PROCESSES_ENVVAR_STRING@,$GA_NUM_PROCESSES_ENVVAR_STRING,;t t
 s,@MEMORY_ALLOC_DEBUG@,$MEMORY_ALLOC_DEBUG,;t t
 s,@MEMORY_ALLOC_SAFE@,$MEMORY_ALLOC_SAFE,;t t
@@ -13666,6 +13715,22 @@ _EOF_
       echo '#define MEMORY_CHUNKS_MIMIC 0' >> $tmpfile
     fi
 
+_EOF_
+
+    cat >> $tmpfile << _EOF_
+
+/*
+ * Explicitly tested headers for this platform:
+ */
+
+_EOF_
+
+    if test x$ac_cv_header_limits_h = xyes; then
+      echo '#define HAVE_LIMITS_H 1' >> $tmpfile
+    else
+      echo '#define HAVE_LIMIT_H 0' >> $tmpfile
+    fi
+
     cat >> $tmpfile << _EOF_
 
 /*
@@ -13720,6 +13785,7 @@ _EOF_
 #define HAVE_SLANG ${HAVE_SLANG}
 #define HAVE_MPI ${HAVE_MPI}
 #define HAVE_PTHREADS ${HAVE_PTHREADS}
+#define USE_OPENMP ${USE_OPENMP}
 #define AVLTREE_KEY_TYPE void *
 #define GA_NUM_PROCESSES_ENVVAR_STRING "${GA_NUM_PROCESSES_ENVVAR_STRING}"
 #define GA_NUM_THREADS_ENVVAR_STRING "${GA_NUM_THREADS_ENVVAR_STRING}"
